services:
  redis:
    image: redis:6.2

  worker:
    image: app-image
    pull_policy: never
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: celery -A app --workdir /code/backend worker -E -l INFO -Q app_queue -P gevent -c 10
    depends_on:
      - redis
    volumes:
      - .:/code
    restart: always

  app:
    image: app-image
    pull_policy: never
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/code
    ports:
      - "${APP_PORT:-8080}:8080"
    command: supervisord -n
    restart: always
